# Generated by Django 5.1.7 on 2025-03-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_galleryimage_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="galleryimage",
            old_name="name",
            new_name="title",
        ),
    ]
