# Generated by Django 5.1.7 on 2025-03-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_order_user_profile_orderlineitem_product_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlineitem",
            name="product_size",
        ),
    ]
