# Generated by Django 5.1.7 on 2025-03-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='special_offer',
            field=models.CharField(blank=True, choices=[('new_arrivals', 'New Arrivals'), ('deals', 'Deals'), ('clearance', 'Clearance'), (None, 'Not a Special Offer')], max_length=20, null=True),
        ),
    ]
